<?xml version="1.0" encoding="utf-8"?><Database Name="TKQClock" Class="TKQClockDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.TinTuc" Member="TinTucs">
    <Type Name="TinTuc">
      <Column Name="MaTT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Img" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETDONDATHANG" Member="CHITIETDONDATHANGs">
    <Type Name="CHITIETDONDATHANG">
      <Column Name="MaDDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Association Name="DonDatHang_CHITIETDONDATHANG" Member="DonDatHang" ThisKey="MaDDH" OtherKey="MaDDH" Type="DonDatHang" IsForeignKey="true" />
      <Association Name="DongHo_CHITIETDONDATHANG" Member="DongHo" ThisKey="MaDH" OtherKey="MaDH" Type="DongHo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonDatHang" Member="DonDatHangs">
    <Type Name="DonDatHang">
      <Column Name="MaDDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayGiao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Tinhtranggiaohang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DonDatHang_CHITIETDONDATHANG" Member="CHITIETDONDATHANGs" ThisKey="MaDDH" OtherKey="MaDDH" Type="CHITIETDONDATHANG" />
      <Association Name="KhachHang_DonDatHang" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DongHo" Member="DongHos">
    <Type Name="DongHo">
      <Column Name="MaDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDH" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ImgUrl" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MoTaNgan" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SoLuongTon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="MaHDH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLoai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ChatLieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Dai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KichThuoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mausac" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Maubanhxe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DongHo_CHITIETDONDATHANG" Member="CHITIETDONDATHANGs" ThisKey="MaDH" OtherKey="MaDH" Type="CHITIETDONDATHANG" />
      <Association Name="HangDongHo_DongHo" Member="HangDongHo" ThisKey="MaHDH" OtherKey="MaHDH" Type="HangDongHo" IsForeignKey="true" />
      <Association Name="LoaiDongHo_DongHo" Member="LoaiDongHo" ThisKey="MaLoai" OtherKey="MaLoai" Type="LoaiDongHo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HangDongHo" Member="HangDongHos">
    <Type Name="HangDongHo">
      <Column Name="MaHDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="HangDongHo_DongHo" Member="DongHos" ThisKey="MaHDH" OtherKey="MaHDH" Type="DongHo" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_DonDatHang" Member="DonDatHangs" ThisKey="MaKH" OtherKey="MaKH" Type="DonDatHang" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiDongHo" Member="LoaiDongHos">
    <Type Name="LoaiDongHo">
      <Column Name="MaLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="LoaiDongHo_DongHo" Member="DongHos" ThisKey="MaLoai" OtherKey="MaLoai" Type="DongHo" />
    </Type>
  </Table>
</Database>